function createfigure_cdata(cdata1)
%CREATEFIGURE(cdata1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 08-Sep-2022 16:17:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create ylabel
ylabel('$\omega$','Interpreter','latex');

% Create xlabel
xlabel('$\Delta$','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 2880.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 25.5]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'ij');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.5,'GridColor',[1 0 0],'Layer','top','TickLabelInterpreter','latex','XTick',...
    [180 360 540 720 900 1080 1260 1440 1620 1800 1980 2160 2340 2520 2700],'XTickLabel',...
    {'$-21q$','$-18q$','$-15q$','$-12q$','$-9q$','$-6q$','$-3q$','$0$','$3q$','$6q$','$9q$','$12q$','$15q$','$18q$','$21q$',''},...
    'YTick',[1 7 13 19 25],'YTickLabel',{'$-\pi$','$\pi / 2$','$0$','$\pi / 2$','$\pi$'});
